@startuml
'https://plantuml.com/sequence-diagram

autonumber

MainLoop -> ActionQueue: ProcessUntilNext()
ActionQueue -> ActionQueue: Foreach a in ActionQueue s.t. delay a < delay player commit a
ActionQueue -> ActionQueue: Commit player action and then SetNewActive
ActionQueue --> ActionQueue: Prune stales
ActionQueue -> ActionQueue: Foreach actor in mons & not in AQ register mons action
ActionQueue -> MainLoop: Return control
@enduml