@startuml
'https://plantuml.com/sequence-diagram

autonumber

Slot -> ActionQueue: ProcessUntilNext
ActionQueue -> ActionQueue: Foreach (actor, action) in aq, \ntake action and query new
'ActionQueue -> ActionQueue: Commit player action and then SetNewActive
'ActionQueue --> ActionQueue: Prune stales
'ActionQueue -> Signal: Return control
@enduml