@startuml
'https://plantuml.com/sequence-diagram

autonumber

'RawKey -> KeyHandle: RawSignal
Slot ->  ContextWrapper: InterpretKey
ContextWrapper --> ContextWrapper: GetContext()
autonumber 2.1
ContextWrapper -> Signal: InterpretKeyWithContext
'Handler -> ContextWrapper: SetIsAction
'ContextWrapper <-> ActionQueue: If isAction: ProcessUntilNext()
'autonumber 2.2
ContextWrapper --> ContextWrapper: SwitchContext()
autonumber 3
ContextWrapper -> Signal: UpdateWithContext
@enduml