@startuml
'https://plantuml.com/sequence-diagram

autonumber

Slot -> MainMenu: Input
MainMenu -> Signal: Save and quit if sigsave/sigquit
MainMenu -> Signal: Load game on sigload
MainMenu -> Signal: New game on signew
@enduml