@startuml
'https://plantuml.com/sequence-diagram

autonumber

'MapHandler -> MapHandler: MapKeyToLocation
MapHandler --> MapHandler: GetNewActive
'autonumber 3.1.1
'MapHandler <-> Map: FindPathTo
'MapHandler -> Signal: CommitPath /' When you move using map screen'/
autonumber 3
MapHandler --> Signal: SetNewActive /' When you move on the map screen '/
autonumber 4
'MapHandler -> Signal: ProcessUntilNext
@enduml